export const cellsData = [
  {
    nomFr: "Conception & CAO",
    nomEn: "Design & CAD",
    descriptionCourteFr:
      "Conception, modélisation 3D et dimensionnement des structures aéronautiques du club.",
    descriptionCourteEn:
      "Design, 3D modelling and structural sizing for the club's aircraft projects.",
    descriptionLongueFr:
      "La cellule Conception & CAO prend en charge la modélisation 3D, le dimensionnement mécanique et la préparation des plans de fabrication pour l'ensemble des projets du club, des drones aux maquettes RC.",
    descriptionLongueEn:
      "The Design & CAD cell handles 3D modelling, mechanical sizing and manufacturing drawings for every club project, from drones to RC scale models.",
    icone: "compass",
    ordre: 1,
    technologies: ["SolidWorks", "CATIA", "Fusion 360"],
    chefNom: "Yassine El Amrani",
    membres: [
      { nom: "Yassine El Amrani", roleFr: "Responsable Cellule", roleEn: "Cell Lead" },
      { nom: "Sara Bennis", roleFr: "Membre Actif", roleEn: "Active Member" },
    ],
    projets: [
      {
        titreFr: "Aile modulaire FX-1",
        titreEn: "FX-1 Modular Wing",
        descriptionFr: "Conception d'une aile démontable pour le drone longue endurance du club.",
        descriptionEn: "Design of a detachable wing for the club's long-endurance drone.",
        statut: "en_cours",
        annee: 2026,
      },
    ],
  },
  {
    nomFr: "Aérodynamique & Mécanique du vol",
    nomEn: "Aerodynamics & Flight Mechanics",
    descriptionCourteFr: "Étude aérodynamique, simulation CFD et optimisation des performances de vol.",
    descriptionCourteEn: "Aerodynamic studies, CFD simulation and flight performance optimisation.",
    descriptionLongueFr:
      "La cellule Aérodynamique modélise l'écoulement autour des profils et des cellules complètes, et exploite les résultats de simulation pour améliorer la finesse et la stabilité des appareils du club.",
    descriptionLongueEn:
      "The Aerodynamics cell models airflow around airfoils and full airframes, using simulation results to improve the lift-to-drag ratio and stability of the club's aircraft.",
    icone: "wind",
    ordre: 2,
    technologies: ["XFLR5", "ANSYS Fluent", "OpenFOAM"],
    chefNom: "Imane Chraibi",
    membres: [
      { nom: "Imane Chraibi", roleFr: "Responsable Cellule", roleEn: "Cell Lead" },
      { nom: "Adam Ziani", roleFr: "Membre Actif", roleEn: "Active Member" },
    ],
    projets: [
      {
        titreFr: "Profil optimisé Falcon-2",
        titreEn: "Falcon-2 Optimised Airfoil",
        descriptionFr: "Simulation CFD comparative de trois profils pour le drone Falcon-2.",
        descriptionEn: "Comparative CFD simulation of three airfoils for the Falcon-2 drone.",
        statut: "termine",
        annee: 2025,
      },
    ],
  },
  {
    nomFr: "Systèmes Embarqués & Avionique",
    nomEn: "Embedded Systems & Avionics",
    descriptionCourteFr: "Électronique embarquée, capteurs et pilotage automatique des appareils du club.",
    descriptionCourteEn: "Onboard electronics, sensors and autopilot systems for the club's aircraft.",
    descriptionLongueFr:
      "La cellule Systèmes Embarqués développe et intègre les cartes de commande, capteurs et liaisons radio qui rendent les appareils du club autonomes et instrumentés.",
    descriptionLongueEn:
      "The Embedded Systems cell develops and integrates the control boards, sensors and radio links that make the club's aircraft autonomous and instrumented.",
    icone: "cpu",
    ordre: 3,
    technologies: ["Arduino", "Pixhawk", "Python", "C++"],
    chefNom: "Othmane Radi",
    membres: [
      { nom: "Othmane Radi", roleFr: "Responsable Cellule", roleEn: "Cell Lead" },
      { nom: "Lina Fassi", roleFr: "Membre Actif", roleEn: "Active Member" },
    ],
    projets: [
      {
        titreFr: "Pilote automatique open-source",
        titreEn: "Open-Source Autopilot",
        descriptionFr: "Intégration d'un contrôleur de vol Pixhawk sur le drone Falcon-2.",
        descriptionEn: "Integration of a Pixhawk flight controller on the Falcon-2 drone.",
        statut: "en_cours",
        annee: 2026,
      },
    ],
  },
  {
    nomFr: "Fabrication & Prototypage",
    nomEn: "Manufacturing & Prototyping",
    descriptionCourteFr: "Impression 3D, découpe et assemblage des prototypes et maquettes du club.",
    descriptionCourteEn: "3D printing, cutting and assembly of the club's prototypes and scale models.",
    descriptionLongueFr:
      "La cellule Fabrication transforme les plans en pièces réelles : impression 3D, découpe CNC, moulage composite et assemblage final des appareils.",
    descriptionLongueEn:
      "The Manufacturing cell turns drawings into physical parts: 3D printing, CNC cutting, composite moulding and final assembly of the aircraft.",
    icone: "wrench",
    ordre: 4,
    technologies: ["Impression 3D", "Découpe CNC", "Composites carbone"],
    chefNom: "Hamza Idrissi",
    membres: [
      { nom: "Hamza Idrissi", roleFr: "Responsable Cellule", roleEn: "Cell Lead" },
      { nom: "Nada Skalli", roleFr: "Membre Actif", roleEn: "Active Member" },
    ],
    projets: [
      {
        titreFr: "Fuselage composite allégé",
        titreEn: "Lightweight Composite Fuselage",
        descriptionFr: "Fabrication d'un fuselage en fibre de carbone pour réduire la masse totale de 18%.",
        descriptionEn: "Manufacturing a carbon-fibre fuselage to cut total mass by 18%.",
        statut: "termine",
        annee: 2025,
      },
    ],
  },
  {
    nomFr: "Logistique & Organisation",
    nomEn: "Logistics & Operations",
    descriptionCourteFr: "Organisation matérielle et coordination des événements du club.",
    descriptionCourteEn: "Material organisation and event coordination for the club.",
    descriptionLongueFr:
      "La cellule Logistique planifie les lieux, le matériel et le calendrier de tous les événements du club, des ateliers hebdomadaires aux Journées Aéronautiques.",
    descriptionLongueEn:
      "The Logistics cell plans venues, equipment and scheduling for every club event, from weekly workshops to the Journées Aéronautiques.",
    icone: "clipboard",
    ordre: 5,
    technologies: ["Notion", "Google Workspace"],
    chefNom: "Salma Ouazzani",
    membres: [
      { nom: "Salma Ouazzani", roleFr: "Responsable Cellule", roleEn: "Cell Lead" },
      { nom: "Mehdi Talbi", roleFr: "Membre Actif", roleEn: "Active Member" },
    ],
    projets: [
      {
        titreFr: "Logistique des Journées Aéronautiques 2026",
        titreEn: "2026 Journées Aéronautiques Logistics",
        descriptionFr: "Coordination du site, des intervenants et du matériel pour l'édition 2026.",
        descriptionEn: "Coordinating the venue, speakers and equipment for the 2026 edition.",
        statut: "en_cours",
        annee: 2026,
      },
    ],
  },
  {
    nomFr: "Sponsoring & Partenariats",
    nomEn: "Sponsoring & Partnerships",
    descriptionCourteFr: "Recherche de financement et relations avec les entreprises partenaires.",
    descriptionCourteEn: "Fundraising and relationship management with partner companies.",
    descriptionLongueFr:
      "La cellule Sponsoring démarche les entreprises du secteur aéronautique et industriel pour financer les projets du club et construire des partenariats durables.",
    descriptionLongueEn:
      "The Sponsoring cell approaches companies in the aerospace and industrial sector to fund the club's projects and build lasting partnerships.",
    icone: "handshake",
    ordre: 6,
    technologies: [],
    chefNom: "Karim Benjelloun",
    membres: [
      { nom: "Karim Benjelloun", roleFr: "Responsable Cellule", roleEn: "Cell Lead" },
      { nom: "Rim Alaoui", roleFr: "Membre Actif", roleEn: "Active Member" },
    ],
    projets: [
      {
        titreFr: "Campagne partenaires 2026",
        titreEn: "2026 Partner Campaign",
        descriptionFr: "Prospection et négociation avec les entreprises du secteur aéronautique marocain.",
        descriptionEn: "Outreach and negotiation with companies in the Moroccan aerospace sector.",
        statut: "en_cours",
        annee: 2026,
      },
    ],
  },
  {
    nomFr: "Communication & Événementiel",
    nomEn: "Communication & Events",
    descriptionCourteFr: "Identité visuelle, réseaux sociaux et animation de la vie du club.",
    descriptionCourteEn: "Visual identity, social media and the club's day-to-day public presence.",
    descriptionLongueFr:
      "La cellule Communication raconte les projets du club au monde extérieur : réseaux sociaux, supports graphiques, photos et vidéos des événements.",
    descriptionLongueEn:
      "The Communication cell tells the club's story to the outside world: social media, graphic materials, and event photography and video.",
    icone: "megaphone",
    ordre: 7,
    technologies: ["Adobe Illustrator", "Premiere Pro"],
    chefNom: "Yasmine Berrada",
    membres: [
      { nom: "Yasmine Berrada", roleFr: "Responsable Cellule", roleEn: "Cell Lead" },
      { nom: "Anas Cherkaoui", roleFr: "Membre Actif", roleEn: "Active Member" },
    ],
    projets: [
      {
        titreFr: "Refonte identité visuelle du club",
        titreEn: "Club Visual Identity Refresh",
        descriptionFr: "Nouvelle charte graphique et supports de communication pour la rentrée 2026.",
        descriptionEn: "New visual identity and communication materials for the 2026 academic year.",
        statut: "termine",
        annee: 2026,
      },
    ],
  },
];

// dates au format [année, mois (1-indexé), jour]
export const eventsData = [
  {
    titreFr: "Journées Aéronautiques 2025",
    titreEn: "Journées Aéronautiques 2025",
    descriptionFr:
      "L'événement phare annuel du club : conférences, ateliers et démonstrations de vol ouverts à tous les étudiants de l'ENSEM.",
    descriptionEn:
      "The club's flagship annual event: talks, workshops and flight demonstrations open to every ENSEM student.",
    dateDebut: [2025, 3, 14],
    dateFin: [2025, 3, 16],
    lieuFr: "Campus ENSEM, Casablanca",
    lieuEn: "ENSEM Campus, Casablanca",
    celluleNom: "Logistique & Organisation",
    statut: "passe",
    inscriptionsOuvertes: false,
    capacite: 300,
    nombreParticipants: 240,
    compteRenduFr: "Trois jours de conférences et de démonstrations, avec plus de 240 participants et douze intervenants du secteur.",
    compteRenduEn: "Three days of talks and demonstrations, with over 240 attendees and twelve industry speakers.",
  },
  {
    titreFr: "Atelier Introduction à la CAO",
    titreEn: "Intro to CAD Workshop",
    descriptionFr: "Prise en main de SolidWorks pour les nouveaux membres, de l'esquisse à la pièce assemblée.",
    descriptionEn: "Hands-on SolidWorks introduction for new members, from sketch to assembled part.",
    dateDebut: [2025, 10, 8],
    dateFin: [2025, 10, 8],
    lieuFr: "Salle informatique B2, ENSEM",
    lieuEn: "Computer Lab B2, ENSEM",
    celluleNom: "Conception & CAO",
    statut: "passe",
    inscriptionsOuvertes: false,
    capacite: 40,
    nombreParticipants: 35,
    compteRenduFr: "Atelier complet, très bon retour des nouveaux membres sur le format pratique.",
    compteRenduEn: "Full workshop, very positive feedback from new members on the hands-on format.",
  },
  {
    titreFr: "Visite industrielle RAM Engineering",
    titreEn: "RAM Engineering Site Visit",
    descriptionFr: "Visite des ateliers de maintenance aéronautique de RAM Engineering à Casablanca.",
    descriptionEn: "Tour of RAM Engineering's aircraft maintenance facilities in Casablanca.",
    dateDebut: [2025, 11, 20],
    dateFin: [2025, 11, 20],
    lieuFr: "RAM Engineering, Aéroport Mohammed V",
    lieuEn: "RAM Engineering, Mohammed V Airport",
    celluleNom: "Logistique & Organisation",
    statut: "passe",
    inscriptionsOuvertes: false,
    capacite: 30,
    nombreParticipants: 28,
    compteRenduFr: "Visite des hangars de maintenance et échange avec les ingénieurs sur les métiers de la maintenance aéronautique.",
    compteRenduEn: "Tour of the maintenance hangars and Q&A with engineers about aircraft maintenance careers.",
  },
  {
    titreFr: "Vol d'essai Falcon-2 v1",
    titreEn: "Falcon-2 v1 Test Flight",
    descriptionFr: "Premier vol d'essai du drone Falcon-2 après intégration du nouveau profil aérodynamique.",
    descriptionEn: "First test flight of the Falcon-2 drone after integrating the new airfoil.",
    dateDebut: [2026, 1, 17],
    dateFin: [2026, 1, 17],
    lieuFr: "Terrain d'essai, Bouskoura",
    lieuEn: "Test field, Bouskoura",
    celluleNom: "Aérodynamique & Mécanique du vol",
    statut: "passe",
    inscriptionsOuvertes: false,
    capacite: 20,
    nombreParticipants: 15,
    compteRenduFr: "Vol d'essai concluant, stabilité en tangage nettement améliorée par rapport à la version précédente.",
    compteRenduEn: "Successful test flight, pitch stability markedly improved over the previous version.",
  },
  {
    titreFr: "Formation Pixhawk & pilote automatique",
    titreEn: "Pixhawk & Autopilot Training",
    descriptionFr: "Formation interne à la configuration et au réglage d'un contrôleur de vol Pixhawk.",
    descriptionEn: "Internal training on configuring and tuning a Pixhawk flight controller.",
    dateDebut: [2026, 3, 4],
    dateFin: [2026, 3, 4],
    lieuFr: "Local du club, ENSEM",
    lieuEn: "Club room, ENSEM",
    celluleNom: "Systèmes Embarqués & Avionique",
    statut: "passe",
    inscriptionsOuvertes: false,
    capacite: 25,
    nombreParticipants: 22,
    compteRenduFr: "Formation suivie par la majorité de la cellule embarqué, base solide pour le projet pilote automatique.",
    compteRenduEn: "Attended by most of the embedded systems cell, a solid base for the autopilot project.",
  },
  {
    titreFr: "Compétition SAE Aero Design",
    titreEn: "SAE Aero Design Competition",
    descriptionFr: "Participation du club à la compétition SAE Aero Design avec l'équipe Fabrication & Prototypage.",
    descriptionEn: "The club's Manufacturing & Prototyping team competing at SAE Aero Design.",
    dateDebut: [2026, 5, 9],
    dateFin: [2026, 5, 11],
    lieuFr: "Fort Worth, États-Unis",
    lieuEn: "Fort Worth, United States",
    celluleNom: "Fabrication & Prototypage",
    statut: "passe",
    inscriptionsOuvertes: false,
    capacite: 8,
    nombreParticipants: 8,
    compteRenduFr: "Première participation du club à une compétition internationale, classement encourageant en catégorie Regular.",
    compteRenduEn: "The club's first international competition entry, an encouraging result in the Regular class.",
  },
  {
    titreFr: "Forum Partenaires Aéronautiques",
    titreEn: "Aerospace Partners Forum",
    descriptionFr: "Rencontres entre le club et les entreprises partenaires pour préparer les projets 2026-2027.",
    descriptionEn: "Meetings between the club and partner companies to prepare the 2026-2027 projects.",
    dateDebut: [2026, 8, 5],
    dateFin: [2026, 8, 9],
    lieuFr: "Campus ENSEM, Casablanca",
    lieuEn: "ENSEM Campus, Casablanca",
    celluleNom: "Sponsoring & Partenariats",
    statut: "en_cours",
    inscriptionsOuvertes: false,
    capacite: 60,
    nombreParticipants: 40,
  },
  {
    titreFr: "Atelier Impression 3D Composite",
    titreEn: "3D Printing & Composites Workshop",
    descriptionFr: "Initiation aux techniques de moulage composite et d'impression 3D appliquées à l'aéronautique.",
    descriptionEn: "Introduction to composite moulding and 3D printing techniques applied to aerospace.",
    dateDebut: [2026, 9, 19],
    dateFin: [2026, 9, 19],
    lieuFr: "Fablab ENSEM",
    lieuEn: "ENSEM Fablab",
    celluleNom: "Fabrication & Prototypage",
    statut: "a_venir",
    inscriptionsOuvertes: true,
    capacite: 30,
    nombreParticipants: 12,
  },
  {
    titreFr: "Journées Aéronautiques 2026",
    titreEn: "Journées Aéronautiques 2026",
    descriptionFr:
      "La grande édition annuelle du club, avec conférences, exposants et démonstrations de vol sur tout le campus.",
    descriptionEn: "The club's big annual edition, with talks, exhibitors and flight demonstrations across campus.",
    dateDebut: [2026, 11, 12],
    dateFin: [2026, 11, 14],
    lieuFr: "Campus ENSEM, Casablanca",
    lieuEn: "ENSEM Campus, Casablanca",
    celluleNom: "Logistique & Organisation",
    statut: "a_venir",
    inscriptionsOuvertes: true,
    capacite: 350,
    nombreParticipants: 87,
  },
  {
    titreFr: "Conférence Métiers de l'Aérospatial",
    titreEn: "Aerospace Careers Conference",
    descriptionFr: "Table ronde avec des ingénieurs et recruteurs du secteur aéronautique marocain.",
    descriptionEn: "Panel discussion with engineers and recruiters from the Moroccan aerospace sector.",
    dateDebut: [2026, 12, 3],
    dateFin: [2026, 12, 3],
    lieuFr: "Amphithéâtre principal, ENSEM",
    lieuEn: "Main auditorium, ENSEM",
    celluleNom: "Communication & Événementiel",
    statut: "a_venir",
    inscriptionsOuvertes: true,
    capacite: 150,
    nombreParticipants: 34,
  },
];

export const partnersData = [
  { nom: "AEROTECH", type: "sponsor", ordre: 1, siteWeb: "", logo: "" },
  { nom: "RAM ENGINEERING", type: "sponsor", ordre: 2, siteWeb: "", logo: "" },
  { nom: "MIDPARC", type: "partenaire", ordre: 3, siteWeb: "", logo: "" },
  { nom: "GIMAS", type: "partenaire", ordre: 4, siteWeb: "", logo: "" },
  { nom: "ENSEM", type: "ecole", ordre: 5, siteWeb: "", logo: "" },
];

export const productsData = [
  {
    nomFr: "T-shirt Club AéroENSEM",
    nomEn: "Club AéroENSEM T-shirt",
    descriptionFr: "T-shirt en coton avec le logo du club, coupe unisexe.",
    descriptionEn: "Cotton t-shirt with the club logo, unisex fit.",
    prix: 120,
    tailles: ["S", "M", "L", "XL"],
    stock: 80,
  },
  {
    nomFr: "Sweat à capuche Club AéroENSEM",
    nomEn: "Club AéroENSEM Hoodie",
    descriptionFr: "Sweat à capuche brodé, floqué au dos avec le slogan du club.",
    descriptionEn: "Embroidered hoodie, back print with the club's motto.",
    prix: 250,
    tailles: ["S", "M", "L", "XL"],
    stock: 40,
  },
  {
    nomFr: "Casquette brodée",
    nomEn: "Embroidered Cap",
    descriptionFr: "Casquette ajustable brodée du logo du club.",
    descriptionEn: "Adjustable cap embroidered with the club logo.",
    prix: 90,
    tailles: [],
    stock: 60,
  },
  {
    nomFr: "Pin's avion collector",
    nomEn: "Collector Aircraft Pin",
    descriptionFr: "Pin's émaillé en édition limitée, modèle du drone Falcon-2.",
    descriptionEn: "Limited-edition enamel pin, modelled on the Falcon-2 drone.",
    prix: 35,
    tailles: [],
    stock: 150,
  },
];

export const boardMembersData = [
  { nom: "Amine Toumi", posteFr: "Président", posteEn: "President", mandat: "2025 - 2026", ordre: 1 },
  { nom: "Hiba Naciri", posteFr: "Vice-Présidente", posteEn: "Vice President", mandat: "2025 - 2026", ordre: 2 },
  { nom: "Ayoub Kabbaj", posteFr: "Trésorier", posteEn: "Treasurer", mandat: "2025 - 2026", ordre: 3 },
  {
    nom: "Meryem Idrissi",
    posteFr: "Secrétaire Générale",
    posteEn: "Secretary General",
    mandat: "2025 - 2026",
    ordre: 4,
  },
  {
    nom: "Zakaria Amrani",
    posteFr: "Responsable Communication",
    posteEn: "Communications Officer",
    mandat: "2025 - 2026",
    ordre: 5,
  },
];

export const statsData = [
  { cle: "membres", labelFr: "Membres", labelEn: "Members", valeur: 128 },
  { cle: "cellules", labelFr: "Cellules", labelEn: "Cells", valeur: 7 },
  { cle: "evenements", labelFr: "Événements organisés", labelEn: "Events run", valeur: 46 },
  { cle: "editions_journees", labelFr: "Éditions des Journées", labelEn: "Editions of the Journées", valeur: 8 },
];

export const siteContentData = [
  {
    cle: "hero_slogan",
    valeurFr: "Together we fly, together we climb the sky.",
    valeurEn: "Together we fly, together we climb the sky.",
  },
  {
    cle: "hero_accroche",
    valeurFr:
      "Sept cellules, une seule trajectoire : transformer la curiosité des étudiants en véritables projets d'ingénierie aéronautique.",
    valeurEn: "Seven cells, one trajectory: turning student curiosity into real aerospace engineering projects.",
  },
  {
    cle: "about_intro",
    valeurFr:
      "Le Club AéroENSEM est l'association étudiante de l'École Nationale Supérieure d'Électricité et de Mécanique dédiée à la passion de l'air et de l'espace. Notre mission est d'offrir un cadre concret où les futurs ingénieurs mettent en pratique leurs connaissances en conception, modélisme, systèmes embarqués et mécanique de vol.",
    valeurEn:
      "Club AéroENSEM brings together students of the École Nationale Supérieure d'Électricité et de Mécanique around a shared passion: flight. Our mission is to give future engineers a concrete setting to apply their knowledge in design, modelling, embedded systems and flight mechanics.",
  },
];
